In [43]:
import pandas as pd
from pathlib import Path
import json

cwd = Path.cwd()
data_dir = cwd / "data"
dataset_path = data_dir / "World_Important_Data.csv"

# Dataset 1 : World Important Events - Ancient to Modern
## Link: https://www.kaggle.com/datasets/saketk511/world-important-events-ancient-to-modern
### Description:
This dataset, "World Important Events - Ancient to Modern," spans significant historical milestones from ancient times to the modern era, covering diverse global incidents. It provides a comprehensive timeline of events that have shaped the world, offering insights into wars, cultural shifts, technological advancements, and social movements.

#### Column Descriptions:
- **Sl. No**: Serial number.
- **Name of Incident**: Title of the event.
- **Date, Month, Year**: When the event occurred.
- **Country**: Where it happened.
- **Type of Event**: Nature of the event (e.g., War, Revolution).
- **Place Name**: Specific location of the event.
- **Impact**: Brief description of the event's impact.
- **Affected Population**: Who was impacted.
- **Important Person/Group Responsible**: Key figures or groups involved.
- **Outcome**: Result of the event (Positive, Negative, Mixed).

In [44]:
dataset_path = data_dir / "World_Important_Data.csv"
df = pd.read_csv(dataset_path)

In [45]:
df

,Sl. No,Name of Incident,Date,Month,Year,Country,Type of Event,Place Name,Impact,Affected Population,Important Person/Group Responsible,Outcome
0,1,Indus Valley Civilization Flourishes,Unknown,Unknown,2600 BC,India,Civilization,Indus Valley,Development of one of the world's earliest urb...,Local inhabitants,Indus Valley people,Positive
1,2,Battle of the Ten Kings,Unknown,Unknown,1400 BC,India,Battle,Punjab,Rigvedic tribes consolidated their control ove...,Rigvedic tribes,Sudas,Positive
2,6,Establishment of the Delhi Sultanate,Unknown,Unknown,1206,India,Political,Delhi,Muslim rule established in parts of India,People of Delhi and surrounding regions,QutbUnknownudUnknowndin Aibak,Mixed
3,7,Battle of Panipat,21,April,1526,India,Battle,Panipat,Foundation of the Mughal Empire in India,Northern Indian kingdoms,Babur,Mixed
4,8,Establishment of British Raj,1,May,1858,India,Colonial,Whole India,Start of direct British governance in India,Indian subcontinent,British East India Company/Empire,Negative
...,...,...,...,...,...,...,...,...,...,...,...,...
1091,1147,First Mexican Empire Declared,28,September,1821,Mexico,Political,Mexico,Brief establishment of an empire soon transiti...,Mexicans,Agustín de Iturbide,Positive
1092,1148,U.S.UnknownMexican War,25,April,1846,Mexico,Military,Northern Mexico,Loss of vast territories to the United States,Mexicans,US,Negative
1093,1149,Reform Wars,Unknown,Unknown,1857,Mexico,Civil War,Mexico,Liberal vs. Conservative conflict leading to c...,Mexicans,Benito Juárez,Mixed
1094,1150,French Intervention in Mexico,Unknown,Unknown,1862,Mexico,Military Intervention,Mexico,Establishment and fall of the Second Mexican E...,Mexicans,Napoleon III,Negative
1095,1151,Mexican Revolution,20,November,1910,Mexico,Revolution,Mexico,Major revolution that transformed Mexican poli...,Mexicans,Francisco I. Madero,Positive

## Cleaning Dataset 1

Dataset1 for the most part contains inforamtion relvenet to data on histotical events.The only column that is not relevant to our project is the outcome column as judging wheter an outcome was postive or negative is not relevant to our project as we are only interested in historical events.
## Dataset Columns after cleaning:
- **Name**: Name of the historical figure (in English).
- **en_curid**: Unique identifier for each individual; maps to the Wikipedia page ID and can be used to access the biography via `http://en.wikipedia.org/?curid=[en_curid]`.
- **Birth Year**: Year the individual was born.
- **Birth City**: City where the individual was born.
- **Country Name**: Commonly accepted name of the country.
- **Continent Name**: Name of the continent associated with the individual.
- **Occupation**: Specific occupation of the individual.
- **Industry**: Broader category grouping related occupations.
- **Domain**: Higher-level category grouping related industries.
- **Gender**: Gender of the individual (Male/Female).

In [46]:
df = df.drop(columns="Outcome")

In [47]:
df = df.rename(columns={
    "Sl. No": "id",
    "Name of Incident": "event_name",
    "Date": "day",
    "Month": "month",
    "Year": "year",
    "Country": "country",
    "Type of Event": "event_type",
    "Place Name": "place_name",
    "Impact": "impact",
    "Affected Population": "affected_population",
    "Important Person/Group Responsible": "responsible_entity"
})

In [48]:
df.columns

Index(['id', 'event_name', 'day', 'month', 'year', 'country', 'event_type',
       'place_name', 'impact', 'affected_population', 'responsible_entity'],
      dtype='str')

## Verifying uniqueness of each row for Dataset 1

In [49]:
df.duplicated().sum()

np.int64(0)

In [50]:
df["id"].nunique(), len(df)

(1096, 1096)

# Dataset 2 : A Manually Verified Dataset of Globally Famous Biographies
## Link: https://www.kaggle.com/datasets/saketk511/world-important-events-ancient-to-modern
### Description:
We present the Pantheon 1.0 dataset: a manually verified dataset of individuals that have transcended linguistic, temporal, and geographic boundaries. The Pantheon 1.0 dataset includes the 11,341 biographies present in more than 25 languages in Wikipedia and is enriched with: (i) manually verified demographic information (place and date of birth, gender) (ii) a taxonomy of occupations classifying each biography at three levels of aggregation and (iii) two measures of global popularity including the number of languages in which a biography is present in Wikipedia (L), and the Historical Popularity Index (HPI) a metric that combines information on L, time since birth, and page-views (2008-2013). We compare the Pantheon 1.0 dataset to data from the 2003 book, Human Accomplishments, and also to external measures of accomplishment in individual games and sports: Tennis, Swimming, Car Racing, and Chess. In all of these cases we find that measures of popularity (L and HPI) correlate highly with individual accomplishment, suggesting that measures of global popularity proxy the historical impact of individuals.

#### Column Descriptions:
- **Name**: Name of the historical figure (in English).
- **en_curid**: Unique identifier for each individual; maps to the Wikipedia page ID and can be used to access the biography via `http://en.wikipedia.org/?curid=[en_curid]`.
- **Country Code (Alpha-2)**: ISO 3166-1 alpha-2 country code based on present-day political boundaries.
- **Country Code (Alpha-3)**: ISO 3166-1 alpha-3 country code based on present-day political boundaries.
- **Country Name**: Commonly accepted name of the country.
- **Continent Name**: Name of the continent associated with the individual.
- **Birth Year**: Year the individual was born.
- **Birth City**: City where the individual was born.
- **Occupation**: Specific occupation of the individual.
- **Industry**: Broader category grouping related occupations.
- **Domain**: Higher-level category grouping related industries.
- **Gender**: Gender of the individual (Male/Female).
- **Total Page Views**: Total Wikipedia page views across all language editions (Jan 2008 – Dec 2013).
- **L\***: Adjusted popularity metric (see dataset appendix for calculation).
- **Number of Languages**: Number of Wikipedia language editions where the biography appears (as of May 2013).
- **Std Page Views**: Standard deviation of page views over time (Jan 2008 – Dec 2013).
- **Page Views (English)**: Total views from the English Wikipedia (Jan 2008 – Dec 2013).
- **Page Views (Non-English)**: Total views from all non-English Wikipedias (Jan 2008 – Dec 2013).
- **Average Views**: Average page views per language edition.
- **HPI (Historical Popularity Index)**: Composite metric measuring historical prominence (see equation (4) in dataset documentation).

In [51]:
dataset_path2 = data_dir / "dataverse_files" / "pantheon.tsv"
df2 = pd.read_csv(dataset_path2, sep="\t")

In [52]:
df2

,en_curid,name,numlangs,birthcity,birthstate,countryName,countryCode,countryCode3,LAT,LON,...,occupation,industry,domain,TotalPageViews,L_star,StdDevPageViews,PageViewsEnglish,PageViewsNonEnglish,AverageViews,HPI
0,307,Abraham Lincoln,131,Hodgenville,KY,UNITED STATES,US,USA,37.571111,-85.738611,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,66145211,5.801387,586914.722000,41477236,24667975,504925.27480,27.938585
1,308,Aristotle,152,Stageira,NaN,Greece,GR,GRC,40.333333,23.500000,...,PHILOSOPHER,PHILOSOPHY,HUMANITIES,56355172,11.914597,201067.460700,15745351,40609821,370757.71050,31.993795
2,339,Ayn Rand,55,Saint Petersburg,NaN,Russia,RU,RUS,59.950000,30.300000,...,WRITER,LANGUAGE,HUMANITIES,14208218,3.175685,87632.490200,11023490,3184728,258331.23640,24.325936
3,595,Andre Agassi,69,Las Vegas,NV,UNITED STATES,US,USA,36.121514,-115.173851,...,TENNIS PLAYER,INDIVIDUAL SPORTS,SPORTS,11244030,6.242525,85553.318100,6353888,4890142,162956.95650,20.925999
4,628,Aldous Huxley,62,Godalming,NaN,UNITED KINGDOM,GB,GBR,51.185000,-0.610000,...,WRITER,LANGUAGE,HUMANITIES,9268920,6.219842,33037.032090,5137256,4131664,149498.70970,25.996605
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11336,38203876,Rebecca,32,Other,NaN,Unknown,UNK,UNK,NaN,NaN,...,RELIGIOUS FIGURE,RELIGION,INSTITUTIONS,1456125,3.958282,3607.911055,954112,502013,45503.90625,25.905977
11337,38239735,Mindaugas,31,Lithuania,NaN,Lithuania,LT,LTU,55.000000,24.000000,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,814092,7.973357,3304.418133,164031,650061,26261.03226,24.958617
11338,38268805,Gediminas of Lithuania,31,Other,NaN,Unknown,UNK,UNK,NaN,NaN,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,737870,9.070608,3047.999702,132408,605462,23802.25806,24.929128
11339,38646961,Eric Hobsbawm,49,Alexandria,NaN,Egypt,EG,EGY,31.200000,29.916667,...,HISTORIAN,HISTORY,HUMANITIES,2557682,7.711120,40990.920320,952975,1604707,52197.59184,23.372257
11340,38707829,Nikolai Chernyshevsky,33,Saratov,NaN,Russia,RU,RUS,51.533333,46.016667,...,WRITER,LANGUAGE,HUMANITIES,615101,6.393447,4589.213995,86510,528591,18639.42424,22.916854

In [53]:
df2.columns

Index(['en_curid', 'name', 'numlangs', 'birthcity', 'birthstate',
       'countryName', 'countryCode', 'countryCode3', 'LAT', 'LON',
       'continentName', 'birthyear', 'gender', 'occupation', 'industry',
       'domain', 'TotalPageViews', 'L_star', 'StdDevPageViews',
       'PageViewsEnglish', 'PageViewsNonEnglish', 'AverageViews', 'HPI'],
      dtype='str')

## Cleaning Dataset 2

Dataset currently has analytical data about wikipedia information that may not be relevant to our project. Although useful for research, analysis these are not useful for our project. We will focus on the dataset that contains information about historical events.

## Dataset Columns after cleaning:
- **Name**: Name of the historical figure (in English).
- **en_curid**: Unique identifier for each individual; maps to the Wikipedia page ID and can be used to access the biography via `http://en.wikipedia.org/?curid=[en_curid]`.
- **Birth Year**: Year the individual was born.
- **Birth City**: City where the individual was born.
- **Country Name**: Commonly accepted name of the country.
- **Continent Name**: Name of the continent associated with the individual.
- **Occupation**: Specific occupation of the individual.
- **Industry**: Broader category grouping related occupations.
- **Domain**: Higher-level category grouping related industries.
- **Gender**: Gender of the individual (Male/Female).

In [54]:
cols_to_keep = [
    "name",
    "en_curid",
    "birthyear",
    "birthcity",
    "countryName",
    "continentName",
    "occupation",
    "industry",
    "domain",
    "gender"
]

df2 = df2[cols_to_keep]

In [55]:
df2 = df2.rename(columns={
    "name": "name",
    "en_curid": "curid",
    "birthyear": "birth_year",
    "birthcity": "birth_city",
    "countryName": "country",
    "continentName": "continent",
    "occupation": "occupation",
    "industry": "industry",
    "domain": "domain",
    "gender": "gender"
})

In [56]:
df2

,name,curid,birth_year,birth_city,country,continent,occupation,industry,domain,gender
0,Abraham Lincoln,307,1809,Hodgenville,UNITED STATES,North America,POLITICIAN,GOVERNMENT,INSTITUTIONS,Male
1,Aristotle,308,-384,Stageira,Greece,Europe,PHILOSOPHER,PHILOSOPHY,HUMANITIES,Male
2,Ayn Rand,339,1905,Saint Petersburg,Russia,Europe,WRITER,LANGUAGE,HUMANITIES,Female
3,Andre Agassi,595,1970,Las Vegas,UNITED STATES,North America,TENNIS PLAYER,INDIVIDUAL SPORTS,SPORTS,Male
4,Aldous Huxley,628,1894,Godalming,UNITED KINGDOM,Europe,WRITER,LANGUAGE,HUMANITIES,Male
...,...,...,...,...,...,...,...,...,...,...
11336,Rebecca,38203876,-3500,Other,Unknown,Unknown,RELIGIOUS FIGURE,RELIGION,INSTITUTIONS,Female
11337,Mindaugas,38239735,1200,Lithuania,Lithuania,Europe,POLITICIAN,GOVERNMENT,INSTITUTIONS,Male
11338,Gediminas of Lithuania,38268805,1275,Other,Unknown,Unknown,POLITICIAN,GOVERNMENT,INSTITUTIONS,Male
11339,Eric Hobsbawm,38646961,1917,Alexandria,Egypt,Africa,HISTORIAN,HISTORY,HUMANITIES,Male
11340,Nikolai Chernyshevsky,38707829,1828,Saratov,Russia,Europe,WRITER,LANGUAGE,HUMANITIES,Male

## Verifying uniqueness of each row for Dataset 2

In [57]:
df2.duplicated().sum()

np.int64(0)

In [58]:
df2["curid"].nunique(), len(df2)

(11341, 11341)

# Dataset 3: World History to 1500: Q&A Dataset
## Link: https://github.com/provos/world-history-to-1500-qa
### Description:
This dataset consists of high-quality question and answer pairs generated from the content of "World History Volume 1: to 1500". The Q&A pairs are designed to cover key historical events, figures, and concepts from prehistory to 1500 CE, providing a comprehensive resource for students, educators, and history enthusiasts.

# Size of Dataset:
2 Columns x 1757 Rows


#### Column Descriptions:
- **Question**: Natural language question related to world history, derived from textbook content. Covers topics such as historical events, figures, civilizations, and key developments within the dataset’s time period.
- **Answer**: Detailed explanatory response to the corresponding question. Provides factual information, contextual background, and historical significance based on the source textbook.

In [60]:
dataset_path3 = data_dir / "WH_QA1.json"
time_period = 'prehistory_to_1500'

with open(dataset_path3, "r") as f:
    data = json.load(f)
df3 = pd.DataFrame(data["qa_pairs"])

In [61]:
df3

,question,answer
0,What was the year of Spartacus's uprising agai...,The **year of Spartacus's uprising** against h...
1,What role did the merging of religious and mil...,The societal structures of the Germanic succes...
2,How did the Centuriate Assembly's voting syste...,The Centuriate Assembly's voting system direct...
3,Who could attend the Plebian Assembly?,Attendance at the Plebian Assembly was strictl...
4,Which large masonry settlement expanded around...,"Around the year **800**, **Pueblo Bonito** in ..."
...,...,...
1752,What are the main differences in construction ...,#### Overview of Effigy vs. Hopewell Mounds\nT...
1753,What were the effects of labor shortages on pe...,"After the Black Death, the labor shortages had..."
1754,What labor regulation was established in Engla...,The labor regulation implemented in England in...
1755,What trend was observed regarding the particip...,The participation of Christians in later crusa...
1756,What were the regions conquered by the Roman E...,The Roman Empire expanded its grain supply sig...

### Cleaning Dataset 3:
The question datasets have no real relatioship that can be created for the SQL table strucutre. However since they are still being added to the SQL table we need to structure to have ID, and maybe informatio about what time period the quesiton is coming from since the two frames will exist soley in one table.

In [62]:
df3["time_period"] = time_period

In [63]:
df3 = df3.reset_index(drop=True)
df3["id"] = df3.index + 1

In [65]:
df3 = df3[[
    "id",
    "question",
    "answer",
    "time_period"
]]

In [68]:
df3.columns

Index(['id', 'question', 'answer', 'time_period'], dtype='str')

## Verifying uniqueness of each row for Dataset 3

In [66]:
df3.duplicated().sum()

np.int64(0)

In [67]:
df3["id"].nunique(), len(df3)

(1757, 1757)

# Dataset 4: World History Since 1500: Q&A Dataset
## Link: https://github.com/provos/world-history-to-1500-qa
### Description:
This dataset consists of high-quality question and answer pairs generated from the content of "World History Since 1500: An Open and Free Textbook". The Q&A pairs are designed to cover key historical events, figures, and concepts from 1500 to the present day, providing a comprehensive resource for students, educators, and history enthusiasts.

# Size of Dataset:
2 Columns x 376 Rows

#### Column Descriptions:
- **Question**: Natural language question related to world history, derived from textbook content. Covers topics such as historical events, figures, civilizations, and key developments within the dataset’s time period.
- **Answer**: Detailed explanatory response to the corresponding question. Provides factual information, contextual background, and historical significance based on the source textbook.

In [19]:
dataset_path4 = data_dir / "WH_QA2.json"
with open(dataset_path4, "r") as f:
    data2 = json.load(f)
df4 = pd.DataFrame(data2["qa_pairs"])

In [20]:
df4

,question,answer
0,What was the impact of Winston Churchill’s 194...,The immediate impact of Churchill's 1946 speec...
1,Who is the author of the work published in 154...,"Published in 1542, *A Short Account of the Des..."
2,Which cities in Japan rose to prominence durin...,"The cities **Kyoto, Osaka, and Edo** were sign..."
3,What specific ways did the Haitian Revolution ...,Napoleon’s plans for a French Empire were hind...
4,What territory did Italy receive in 1866 after...,The outcome of the Austro-Prussian War in 1866...
...,...,...
371,Which powerful states were founded by West Afr...,The rise of the transatlantic trade in the 17t...
372,What significant action did the National Assem...,"In the wake of the storming of the Bastille, o..."
373,How did Soviet officials undermine the pledge ...,"After World War II, the Soviet Union's actions..."
374,Who began the production of the Model-T Ford a...,The year **1908** marked a significant milesto...
375,What was the name of the treaty signed between...,"In 1922, Weimar Germany and the Soviet Union s..."

### Cleaning Dataset 4:
The question datasets have no real relatioship that can be created for the SQL table strucutre. However since they are still being added to the SQL table we need to structure to have ID, and maybe informatio about what time period the quesiton is coming from since the two frames will exist soley in one table.

In [69]:
time_period = '1500_to_present'
df4["time_period"] = time_period

In [70]:
df4 = df4.reset_index(drop=True)
df4["id"] = df4.index + 1

In [71]:
df4 = df4[[
    "id",
    "question",
    "answer",
    "time_period"
]]

In [72]:
df4.columns

Index(['id', 'question', 'answer', 'time_period'], dtype='str')

## Verifying uniqueness of each row for Dataset 4

In [73]:
df4.duplicated().sum()

np.int64(0)

In [74]:
df4["id"].nunique(), len(df4)

(376, 376)

## Saving Datasets
To help project strucuture clean and organized this section where I cleaned the data is a seperate
part from the postgres upload to Neon. With that being said the upload will be done in the file :

In [75]:
df.to_csv("historical_events_core.csv", index=False)

In [76]:
df2.to_csv("historical_figures.csv", index=False)

In [77]:
df3.to_csv("qa_pairs1.csv", index=False)

In [78]:
df4.to_csv("qa_pairs2.csv", index=False)