In [3]:
import pandas as pd
main = pd.read_parquet("data/Neurips_HiST-LLM.parquet")
ref = pd.read_parquet("data/references.parquet")

In [4]:
main.head()

,additional_review,description,id,ref_id,Q,message,g_message,A,polity_old_id,start_year_str,...,gpt-3.5-turbo-0125-answer,gpt-3.5-turbo-0125-system_fingerprint,meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo-full_response,meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo-answer,meta-llama/Llama-3-70b-chat-hf-full_response,meta-llama/Llama-3-70b-chat-hf-answer,meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo-full_response,meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo-answer,gemini-1.5-flash-full_response,gemini-1.5-flash-answer
0,True,e.g. Justinian Dynasty. Reforms of Diocletian ...,33706,4JHY9IIM,Question:\nThe characteristic 'elite status is...,"[{""role"": ""system"", ""content"": ""You are a hist...","[{""role"": ""user"", ""parts"": [""You will be taske...",A,TrERom*,395 CE,...,A,None,"The Roman aristocracy was largely hereditary, ...",A,"The Roman Empire, including the Eastern Roman ...",A,"The East Roman Empire, also known as the Byzan...",A,The East Roman Empire was a continuation of th...,A
1,True,,14775,34REAN6A,Question:\nThe characteristic 'Couriers' is ca...,"[{""role"": ""system"", ""content"": ""You are a hist...","[{""role"": ""user"", ""parts"": [""You will be taske...",A,IqNAssr,911 BCE,...,A,None,The Neo-Assyrian Empire had a well-developed p...,A,The Neo-Assyrian Empire had a well-organized s...,A,The Neo-Assyrian Empire had a well-organized s...,A,The Neo-Assyrian Empire had a well-developed p...,A
2,False,Cannons and firearms first used by the Song.,48894,DRH5S2XA,Question:\nThe characteristic 'Handheld firear...,"[{""role"": ""system"", ""content"": ""You are a hist...","[{""role"": ""user"", ""parts"": [""You will be taske...",D,CnTangE,617 CE,...,C,None,No evidence of handheld firearms in the Tang D...,D,Handheld firearms were not invented until the ...,D,"The first handheld firearm, the fire lance, wa...",D,The Tang Dynasty was a pre-gunpowder era.\nAns...,D
3,True,The behaviors described by Gjerset seem to sug...,29490,GJDJ6MTB,Question:\nThe characteristic 'Examination sys...,"[{""role"": ""system"", ""content"": ""You are a hist...","[{""role"": ""user"", ""parts"": [""You will be taske...",D,NorKing,1262 CE,...,D,None,"The Kingdom of Norway II was a feudal society,...",D,No evidence of examination system in medieval ...,D,The examination system was a characteristic of...,D,The Norwegian king Magnus VI (1263-1280) estab...,C
4,False,"""In the Holy Land the <...> knights and great ...",65294,BPLB8D2W,Question:\nThe characteristic 'Ideological tho...,"[{""role"": ""system"", ""content"": ""You are a hist...","[{""role"": ""user"", ""parts"": [""You will be taske...",A,FrValoE,1328 CE,...,A,None,The ideology of the French monarchy during thi...,A,"The concept of ""natural lordship"" and the idea...",D,"The concept of ""noble"" and ""commoner"" was well...",C,The French Kingdom during this period was mark...,A

In [11]:
question = main.loc[3, 'Q']
answer = main.loc[3, 'A']

In [12]:
question

"Question:\nThe characteristic 'Examination system' is categorized under 'Bureaucracy characteristics'. Was it present, inferred present, inferred absent, or absent for the polity called 'Kingdom of Norway II', during the time frame from 1262 CE to 1380 CE?\nOptions:\nA: Present, B: Inferred Present, C: Inferred Absent, D: Absent\nReasoning and evidence:\n"

In [13]:
ref.head()

,Key,Item Type,Publication Year,Author,Title,Publication Title,ISBN,ISSN,DOI,Url,...,Programming Language,Version,System,Code,Code Number,Section,Session,Committee,History,Legislative Body
0,SAS9TRAT,book,1993,"Marcus, Joyce",,,,,,,...,,,,,,,,,,
1,RKRHHKX8,bookSection,2013,"Kosmin, Paul J.",Alexander the Great and the Seleucids in Iran,The Oxford Handbook of Ancient Iran,978-0-19-973330-9,,,https://www.oxfordhandbooks.com/view/10.1093/o...,...,,,,,,,,,,
2,J89W37CN,book,2007,"Yaran, Cafer S.",Understanding Islam,,1-903765-30-7,,,,...,,,,,,,,,,
3,DVINDTEE,book,2011,"蔡燕歆; Steinhardt, Nancy",Chinese Architecture,,978-0-521-18644-5,,,,...,,,,,,,,,,
4,NZ3XZHQK,bookSection,1994,"Harmatta, János",Languages and literature in the Kushan Empire,"History of civilizations of Central Asia, v. 2...",,,,,...,,,,,,,,,,